2020-11-07 16:10:01: Cloning into '/home/volumio/crawler/service/_repo'...
2020-11-07 16:10:01: fatal: unable to access 'https://shiehnpin:vu%2C4p%20qu%2F6@github.com/shiehnpin/crawler-data.git/': Could not resolve host: github.com
2020-11-07 16:10:01: 
